### ISSUE TITLE
"{runtime.tools.avrdude.path}/bin/avrdude"

### ISSUE THREAD

**Issue by gepd** [gepd/Stino#1]
After the new installation process, the plugins is almost working it compiles the code, but shows an error when it tries to upload it. (with IDE 1.6.4)

**Error:**

`"{runtime.tools.avrdude.path}/bin/avrdude" "-C{runtime.tools.avrdude.path}/etc/avrdude.conf" -v -patmega328p -carduino "-PCOM10" -b115200 -D "`

I modify the `platform_wiring.txt` and `platform_avr.txt` based on the `platform.txt` file located in `arduino-1.6.4\hardware\arduino\avr`

but the error keeps

**Comment by DrSensor** [comment]
same here but the error just
/bin/sh: 1: {runtime.tools.avrdude.path}/bin/avrdude: not found

**Comment by gepd** [comment]
I've solve this issue for IDE version 1.6.4, now you can upload you code without problem

**Comment by ghost** [comment]
Hi,
Issus isn´t fixed. I use IDE 1.6.4 with Windows 7 x64. Clean install of Sublime and new-Stino like the updates installion guide.

**Comment by jordlynn** [comment]
The issue still exists, tried clean install of ST3 and Stino error message is the same as @cimenx seems like the path is broken somewhere.

**Comment by gepd** [comment]
I'm looking in this issue, seems like It happen in W7, I've to install W7 to start to debug it

**Comment by jordlynn** [comment]
I'm running Arch Linux, so it's happening across systems. Thanks for the quick reply, I'll let you know if I get it fixed. Also an error code if it helps `Stino - Exit with error code 127.`

**Comment by jordlynn** [comment]
Okay aparently the commit https://github.com/gepd/Stino/commit/cdbe58eadf01031aa0becdc4fd0a2af026555410 didn't get pulled from Package Control? And when I'm downloading from a .zip file the changes aren't present there either. Maybe I'm missing something obvious?

**Comment by gepd** [comment]
> Maybe I'm missing something obvious?

Not as I know. 

Is your zip file named like `Stino-cdbe58eadf01031aa0becdc4fd0a2af026555410.zip` ? I had download the zip file and all seems to be good.

As I'm not the owner of the code, these error code doesn't mean anything to me, Robot-Will never post a documentation with the meaning of the codes, but there something else we can do.

Please go to `Arduino-> Build options` and check `Show Compilation Output` and `Show Upload Output`

Try to upload your sketch and copy the entirely error. It may help me to know where can be the error

**Comment by jordlynn** [comment]
I am no longer getting the error code so I can't post my output. But the entirety of the error is the same as what @cimenx posted above.

I fixed the issue by going through and manually editing the code that https://github.com/gepd/Stino/commit/cdbe58eadf01031aa0becdc4fd0a2af026555410 changed. For some reason if you add the package through package control you get an older version. Or at least not from the new-stino branch. Instead I'm pretty sure it's pull from master.

I don't think it matters but the filename is Stino-new-stino.zip but it doesn't have those latest changes inside.

**Comment by gepd** [comment]
Currently is not possible to install the plugin by the package control automatically, instead, you have to do it manually as is detailed in the "Installation" section here: https://github.com/gepd/Stino

**Comment by jordlynn** [comment]
The instructions say to install using Package Control after you've added the repository to it, which is exactly what I did at least. I have no idea what causes the discrepancy between the stino-new and what actually gets downloaded .
