### ISSUE TITLE
complile problems with atmega 2560

### ISSUE THREAD

**Issue by vMeph** [gepd/Stino#12]
when i select atmega 2560 board and try complie a sketch a file called eeprom.h will open with the folowing errors, any ideas how to fix?

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h: In function 'void eeprom_read_block(void_, const void_, size_t)':

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h:290: error: ISO C++ forbids incrementing a pointer of type 'void*'

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h:290: error: ISO C++ forbids incrementing a pointer of type 'const void*'

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h:290: error: invalid conversion from 'const void_' to 'const uint8_t_'

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h:290: error:   initializing argument 1 of 'uint8_t eeprom_read_byte(const uint8_t*)'

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h:290: error: lvalue required as left operand of assignment

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h: In function 'void eeprom_write_block(const void_, void_, size_t)':

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h:400: error: expected primary-expression before '}' token

c:/winavr-20090313/lib/gcc/../../avr/include/avr/eeprom.h:400: error: expected `;' before '}' token

**Comment by gepd** [comment]
Hi @Encarnacao I'm working in a new plugin it's not using the arduino IDE instead use [platformIO](http://platformio.org/) as compiler, you shouldn't have problem to run any arduino board (it support more than 200 boards). It is currently in beta, if you like to try it and maybe report an error/bug or new feature, you will be welcome.

All the details about the project here:
https://github.com/gepd/Deviot
