### ISSUE TITLE
Doesn't Play Well with Processing Plugin for Sublime

### ISSUE THREAD

**Issue by claybudin** [gepd/Stino#13]
Hi,

Your tool is very nice.  However, it appears to associate files with the .pde extension with the Arduino.  That means that Processing files (which also end in .pde) are diverted from their normal association.  So, I can seem to use this tool with the Processing Sublime Text plugin (https://github.com/b-g/processing-sublime).

I think all you need to do is to remove the association to .pde files.  Most current Arduino source files end in .ino these days so I don't think that's asking too much.

Also, it looks like you associate .c .cc and .h files with Arduino as well.  Is that a good idea?  There are many, many .c etc. files out there which aren't Arduino-specific files.

Thanks,
Clay Budin
NYC

**Comment by gepd** [comment]
Hi claybudin, 
first to all I'm not the developer of this plugin, I forked to made some changes 
This is the fist developer github https://github.com/Robot-Will/Stino 
But he is not developing it anymore.

As I understand Processing has other way to code (write mode), I don't know if is only a thing of the extension.

The thing is, this plugin need to be re writed to work with all the new IDE versions. I think, will be difficult to someone work trying this, It does not get much cooperation this aspect.

**Comment by claybudin** [comment]
Hi Guillermo,

Thanks for getting back to me.

After experimenting, it seems like I can't run Processing after I run
Arduino.  So, if I upload
new code to the Arduino, I have to quit and restart Sublime and then I can
run my Processing
sketch.  It's a bit of a pain, but better than using the built-in IDEs for
either Arduino or Processing.

I was hoping it would be a quick fix, but if not, I can live with things
the way they are.

Thanks,

Clay Budin
NYC
