### ISSUE TITLE
OS X 10.10.5 Permission Error

### ISSUE THREAD

**Issue by fletchjeff** [gepd/Stino#14]
I have installed the current version of Stino, but when I run Verify/Compile, I get:

`/Applications/arduino.app/Contents/Java/hardware/tools/avr/bin/avr-ar: {archive_file_path}: Permission denied`

The file permissions for avr-ar are correct, and I can run it normally. Any ideas?

**Comment by dean-wong** [comment]
1. find "arduino_compiler.py" file in stino;
2. goto line 315;
3. change
   
   ```
    cmd = ar_cmd.replace('{object_file}', obj_path) 
   ```
   
   to
   
   ```
   cmd = ar_cmd.replace('{archive_file_path}', core_archive_path)
   cmd = cmd.replace('{object_file}', obj_path)
   ```
4. restart sublime.
