### ISSUE TITLE
Compiling works, but uploading runs into an error

### ISSUE THREAD

**Issue by fstoltz** [gepd/Stino#24]
[Stino - Start uploading...]
avrdude: can't open config file "/usr/share/arduino/hardware/tools/avr/etc/avrdude.conf": No such file or directory
avrdude: error reading system wide configuration file "/usr/share/arduino/hardware/tools/avr/etc/avrdude.conf"

[Stino - Exit with error code 1.]

Anyone have a clue? Haven't got any luck so far, I've tried different versions of Sublime Text 2/3. And also different ways of installing Arduino onto Sublime. (Extracted ZIP into package folder, and using github repository).

Running Linux Mint 64-bit

Cheers.﻿

**Comment by paulosaloto** [comment]
Had the same issue, fixed it changing lines 85 and 86 of this file:
/.config/sublime-text-3/Packages/Stino/preset/platform_avr.txt
`tools.avrdude.cmd.path={path}/avrdude`
`tools.avrdude.config.path={path}/avrdude.conf`

And then change line 323 at:
/home/paulo/.config/sublime-text-3/Packages/Stino/stino/pyarduino/arduino_target_params.py
`    target_tools_avrdude_path = os.path.join(ide_path, 'hardware/tools')`

I'm really not sure if this is the best solution, but worked for me.
found this solution [here](https://github.com/Robot-Will/Stino/issues/189)

**Comment by fstoltz** [comment]
Tried it & others' proposed solutions, but didn't work for me.

Thanks anyways.
