### ISSUE TITLE
Cannot find the package of Stino

### ISSUE THREAD

**Issue by Super169** [gepd/Stino#3]
I just reinstall my workstation with Sublime Text 3 installed.

And I try to add Stino back, but I cannot find the package for Stino even I have installed Package Control and add the repo link to Repository.  I don't know if this is the problem in my internet connection, but it can display the default package, also the one called "Arduino-Like IDE", and I can visit this github entry via Chrome; however, it cannot get the package here.

Could you please also provide the installation package, so that it can be installed by manual procedure as before?

Thanks in advance.

**Comment by gepd** [comment]
you can fix this problem installing the plugin as is described in the installation instructions: https://github.com/gepd/Stino#installation

**Comment by Super169** [comment]
I just encounter the problem when following the above instruction, in step 4.

Open the Command Palette again and run the 'Package Control: Install Package' command and choose the package named 'Stino'. Be sure you don't choose the package in the default repository called 'Arduino-Like IDE.'

But the package of 'Stino' did not show.

So I just download the zip from github, and extract to Packages folder, and it seems that it can be installed by sublime.  But I don't know if there will have any problem when I need to update Stino again later.

**Comment by gepd** [comment]
Some people had some problems with manually installation, after copied the stino folder, this was removed. Your problem seems to be when you add the new repo, no one has been reported this problem
