### ISSUE TITLE
Verify/Upload error

### ISSUE THREAD

**Issue by jzck** [gepd/Stino#6]
Same error for any code:

```
[Stino - Start building "testtest"...]
[  3%] Creating /tmp/Stino_build/testtest/testtest.ino.cpp.o...
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file

[Stino - Exit with error code 2.]
```

I'm setting up stint because the basic arduino IDE is crap, to get around this I compile ST3 ion code with another ST3 plugin (arduino-cli). Please help.

EDIT: forgot to mention i'm on mac osX

**Comment by gepd** [comment]
can you upload the `testtest.ino` file?
that error is not related with the previous issues.

**Comment by jzck** [comment]
This error occurs with any file, i tried verify/upload on example sketches too (blinky led) and it does the same, so i'm pretty sure the problem is from stint and not the file

**Comment by jzck** [comment]
example with :

```
void setup() {
  // initialize digital pin 13 as an output.
  pinMode(13, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(13, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);              // wait for a second
  digitalWrite(13, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);              // wait for a second
}
```

I get :

``````
[Stino - Start building "Blink"...]
[  3%] Creating /tmp/Stino_build/Blink/Blink.ino.cpp.o...
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file

[Stino - Exit with error code 2.]```
``````

**Comment by gepd** [comment]
I'll look the code to see what it can be.
At least in my test I don't receive that error, but I'm using windows, so I'll try in linux

**Comment by jzck** [comment]
It's 100% not code related though, the code compiles fine on the basic arduino IDE

**Comment by gepd** [comment]
I'm sorry, I mean the stino code

**Comment by gepd** [comment]
I've add a new fix base on https://github.com/gepd/Stino/issues/7 please update the the plugin and tell me if it fix your problem

**Comment by jzck** [comment]
nope didn't work

**Comment by gepd** [comment]
To help to understand the error please follow the next steps:

mark `"Show compilation output" in the menu Arduino-> Build Options`
mark `"Show upload output" in the menu Arduino-> Build Options`

After this, try to upload the sketch and copy the error and paste here.

**Comment by jzck** [comment]
yes, there's an extra error paragraph: 

```
[Stino - Start building "BareMinimum"...]
[  3%] Creating /tmp/Stino_build/BareMinimum/BareMinimum.ino.cpp.o...
"avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD  -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/examples/01.Basics/BareMinimum" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "/tmp/Stino_build/BareMinimum/BareMinimum.ino.cpp" -o "/tmp/Stino_build/BareMinimum/BareMinimum.ino.cpp.o"
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file

[Stino - Exit with error code 2.]
```

for the sketch:

```
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}

```

please note that this is the first time i'm using STino, so this may all be just something I forgot or didn't do whilst setting things up.

**Comment by jzck** [comment]
so basically just added the very long line : 

```
"avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD  -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/Applications/Arduino.app/Contents/Java/examples/01.Basics/BareMinimum" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino" "-I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/standard" "/tmp/Stino_build/BareMinimum/BareMinimum.ino.cpp" -o "/tmp/Stino_build/BareMinimum/BareMinimum.ino.cpp.o"
```

**Comment by gepd** [comment]
Can you please paste too the console output?
Menu View->Show Console

I'm working to fix that, as I don't have a mac on my side can be took a little more to fix it

**Comment by jzck** [comment]
console says:

```
/Applications/Arduino.app/Contents/MacOS/Arduino --board arduino:avr:uno --upload /Users/jackhalford/Desktop/Arduino Sketchbook/testc/testc.ino --port /dev/tty.usbmodem1411
b''
Unable to open /Users/jackhalford/Library/Application Support/Sublime Text 3/Packages/User/arduino-cli.sublime-settings
```

but when i verify/compile it closes console and shows the previous error message

**Comment by jzck** [comment]
So I've tried removing the `arduino-cli` package, and now the console is empty.

**Comment by gepd** [comment]
It shows the same error when you use `upload`?

**Comment by jzck** [comment]
Yes it does, although i don't have an arduino board plugged in right now, so i'm not sure how the `upload` command works when theres no board

**Comment by gepd** [comment]
I have add a new fix base on this discussion https://github.com/Robot-Will/Stino/issues/294
Tell me if that fix the current issue

**Comment by jzck** [comment]
installed v2015.08.02.17.52.34

Still same error.

**Comment by gepd** [comment]
Can you install the plugin and the ST again? the people who had trouble with the plugin in OS X they resolved it with the latest update.

**Comment by jzck** [comment]
Don't know how to clean until an app on mac, so I installed ST2 and it now works fine, thanks a lot.
